class AutogeneratedLogin {
  SoapEnvelope? soapEnvelope;

  AutogeneratedLogin({this.soapEnvelope});

  AutogeneratedLogin.fromJson(Map<String, dynamic> json) {
    soapEnvelope = json['soap:Envelope'] != null
        ? new SoapEnvelope.fromJson(json['soap:Envelope'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.soapEnvelope != null) {
      data['soap:Envelope'] = this.soapEnvelope!.toJson();
    }
    return data;
  }
}

class SoapEnvelope {
  SoapBody? soapBody;

  SoapEnvelope({this.soapBody});

  SoapEnvelope.fromJson(Map<String, dynamic> json) {
    soapBody = json['soap:Body'] != null
        ? new SoapBody.fromJson(json['soap:Body'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.soapBody != null) {
      data['soap:Body'] = this.soapBody!.toJson();
    }
    return data;
  }
}

class SoapBody {
  LoginUtenteResponse? loginUtenteResponse;

  SoapBody({this.loginUtenteResponse});

  SoapBody.fromJson(Map<String, dynamic> json) {
    loginUtenteResponse = json['LoginUtenteResponse'] != null
        ? new LoginUtenteResponse.fromJson(json['LoginUtenteResponse'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.loginUtenteResponse != null) {
      data['LoginUtenteResponse'] = this.loginUtenteResponse!.toJson();
    }
    return data;
  }
}

class LoginUtenteResponse {
  LoginUtenteResult? loginUtenteResult;

  LoginUtenteResponse({this.loginUtenteResult});

  LoginUtenteResponse.fromJson(Map<String, dynamic> json) {
    loginUtenteResult = json['LoginUtenteResult'] != null
        ? new LoginUtenteResult.fromJson(json['LoginUtenteResult'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.loginUtenteResult != null) {
      data['LoginUtenteResult'] = this.loginUtenteResult!.toJson();
    }
    return data;
  }
}

class LoginUtenteResult {
  List<Valori>? valori;

  LoginUtenteResult({this.valori});

  LoginUtenteResult.fromJson(Map<String, dynamic> json) {
    if (json['Valori'] != null) {
      valori = <Valori>[];
      json['Valori'].forEach((v) {
        valori!.add(new Valori.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.valori != null) {
      data['Valori'] = this.valori!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Valori {
  String? value;
  String? description;
  String? count;

  Valori({this.value, this.description, this.count});

  Valori.fromJson(Map<String, dynamic> json) {
    value = json['Value'];
    description = json['Description'];
    count = json['Count'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['Value'] = this.value;
    data['Description'] = this.description;
    data['Count'] = this.count;
    return data;
  }
}