class AutogeneratedExpositor {
  SoapEnvelope? soapEnvelope;

  AutogeneratedExpositor({this.soapEnvelope});

  AutogeneratedExpositor.fromJson(Map<String, dynamic> json) {
    soapEnvelope = json['soap:Envelope'] != null
        ? new SoapEnvelope.fromJson(json['soap:Envelope'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.soapEnvelope != null) {
      data['soap:Envelope'] = this.soapEnvelope!.toJson();
    }
    return data;
  }
}

class SoapEnvelope {
  SoapBody? soapBody;

  SoapEnvelope({this.soapBody});

  SoapEnvelope.fromJson(Map<String, dynamic> json) {
    soapBody = json['soap:Body'] != null
        ? new SoapBody.fromJson(json['soap:Body'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.soapBody != null) {
      data['soap:Body'] = this.soapBody!.toJson();
    }
    return data;
  }
}

class SoapBody {
  GetUsersExtraResponse? getUsersExtraResponse;

  SoapBody({this.getUsersExtraResponse});

  SoapBody.fromJson(Map<String, dynamic> json) {
    getUsersExtraResponse = json['GetUsersExtraResponse'] != null
        ? new GetUsersExtraResponse.fromJson(json['GetUsersExtraResponse'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.getUsersExtraResponse != null) {
      data['GetUsersExtraResponse'] = this.getUsersExtraResponse!.toJson();
    }
    return data;
  }
}

class GetUsersExtraResponse {
  GetUsersExtraResult? getUsersExtraResult;

  GetUsersExtraResponse({this.getUsersExtraResult});

  GetUsersExtraResponse.fromJson(Map<String, dynamic> json) {
    getUsersExtraResult = json['GetUsersExtraResult'] != null
        ? new GetUsersExtraResult.fromJson(json['GetUsersExtraResult'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.getUsersExtraResult != null) {
      data['GetUsersExtraResult'] = this.getUsersExtraResult!.toJson();
    }
    return data;
  }
}

class GetUsersExtraResult {
  List<Miatabella>? miatabella;

  GetUsersExtraResult({this.miatabella});

  GetUsersExtraResult.fromJson(Map<String, dynamic> json) {
    if (json['Miatabella'] != null) {
      miatabella = <Miatabella>[];
      try {
        json['Miatabella'].foreach((v) {
          miatabella!.add(new Miatabella.fromJson(v));
        });
      } catch (e) {
        miatabella!.add(new Miatabella.fromJson(json['Miatabella']));
      }
    }
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.miatabella != null) {
      data['Miatabella'] = this.miatabella!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Miatabella {
  String? idextra;
  String? idparent;
  String? idmanifestazione;
  String? admin;
  String? titolidisponibili;
  String? nome;
  String? cognome;
  Null? ragionesociale;
  String? email;
  Null? cap;
  Null? telefono;
  Null? note;
  String? siglanazione;
  String? siglaprovincia;
  String? idtipologia;
  String? codice20;

  Miatabella(
      {this.idextra,
      this.idparent,
      this.idmanifestazione,
      this.admin,
      this.titolidisponibili,
      this.nome,
      this.cognome,
      this.ragionesociale,
      this.email,
      this.cap,
      this.telefono,
      this.note,
      this.siglanazione,
      this.siglaprovincia,
      this.idtipologia,
      this.codice20});

  Miatabella.fromJson(Map<String, dynamic> json) {
    idextra = json['Idextra'];
    idparent = json['Idparent'];
    idmanifestazione = json['Idmanifestazione'];
    admin = json['Admin'];
    titolidisponibili = json['Titolidisponibili'];
    nome = json['Nome'];
    cognome = json['Cognome'];
    ragionesociale = json['Ragionesociale'];
    email = json['Email'];
    cap = json['Cap'];
    telefono = json['Telefono'];
    note = json['Note'];
    siglanazione = json['Siglanazione'];
    siglaprovincia = json['Siglaprovincia'];
    idtipologia = json['Idtipologia'];
    codice20 = json['Codice20'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['Idextra'] = this.idextra;
    data['Idparent'] = this.idparent;
    data['Idmanifestazione'] = this.idmanifestazione;
    data['Admin'] = this.admin;
    data['Titolidisponibili'] = this.titolidisponibili;
    data['Nome'] = this.nome;
    data['Cognome'] = this.cognome;
    data['Ragionesociale'] = this.ragionesociale;
    data['Email'] = this.email;
    data['Cap'] = this.cap;
    data['Telefono'] = this.telefono;
    data['Note'] = this.note;
    data['Siglanazione'] = this.siglanazione;
    data['Siglaprovincia'] = this.siglaprovincia;
    data['Idtipologia'] = this.idtipologia;
    data['Codice20'] = this.codice20;
    return data;
  }
}
