import '../expositor_mapper/expositor_mapper.dart';

class AutogeneratedExpositor {
  SoapEnvelope? soapEnvelope;

  AutogeneratedExpositor({this.soapEnvelope});

  AutogeneratedExpositor.fromJson(Map<String, dynamic> json) {
    soapEnvelope = json['soap:Envelope'] != null
        ? new SoapEnvelope.fromJson(json['soap:Envelope'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.soapEnvelope != null) {
      data['soap:Envelope'] = this.soapEnvelope!.toJson();
    }
    return data;
  }
}

class SoapEnvelope {
  SoapBody? soapBody;

  SoapEnvelope({this.soapBody});

  SoapEnvelope.fromJson(Map<String, dynamic> json) {
    soapBody = json['soap:Body'] != null
        ? new SoapBody.fromJson(json['soap:Body'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.soapBody != null) {
      data['soap:Body'] = this.soapBody!.toJson();
    }
    return data;
  }
}

class SoapBody {
  GetUsersExtraResponse? getUsersExtraResponse;

  SoapBody({this.getUsersExtraResponse});

  SoapBody.fromJson(Map<String, dynamic> json) {
    getUsersExtraResponse = json['GetUsersExtraResponse'] != null
        ? new GetUsersExtraResponse.fromJson(json['GetUsersExtraResponse'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.getUsersExtraResponse != null) {
      data['GetUsersExtraResponse'] = this.getUsersExtraResponse!.toJson();
    }
    return data;
  }
}

class GetUsersExtraResponse {
  GetUsersExtraResult? getUsersExtraResult;

  GetUsersExtraResponse({this.getUsersExtraResult});

  GetUsersExtraResponse.fromJson(Map<String, dynamic> json) {
    getUsersExtraResult = json['GetUsersExtraResult'] != null
        ? new GetUsersExtraResult.fromJson(json['GetUsersExtraResult'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.getUsersExtraResult != null) {
      data['GetUsersExtraResult'] = this.getUsersExtraResult!.toJson();
    }
    return data;
  }
}

class GetUsersExtraResult {
  List<ExpoisitorMapper>? miatabella;

  GetUsersExtraResult({this.miatabella});

  GetUsersExtraResult.fromJson(Map<String, dynamic> json) {
    if (json['Miatabella'] != null) {
      miatabella = <ExpoisitorMapper>[];
      try {
        for (var expositor in json['Miatabella']) {
          miatabella!.add(new ExpoisitorMapper.fromJson(expositor));
        }
      } catch (e) {
        miatabella!.add(new ExpoisitorMapper.fromJson(json['Miatabella']));
      }
    }
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.miatabella != null) {
      data['Miatabella'] = this.miatabella!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}
