import '../expositor_mapper/expositor_mapper.dart';

class AutogeneratedExpositorDetailResponse {
  SoapEnvelope? soapEnvelope;

  AutogeneratedExpositorDetailResponse({this.soapEnvelope});

  AutogeneratedExpositorDetailResponse.fromJson(Map<String, dynamic> json) {
    soapEnvelope = json['soap:Envelope'] != null
        ? new SoapEnvelope.fromJson(json['soap:Envelope'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.soapEnvelope != null) {
      data['soap:Envelope'] = this.soapEnvelope!.toJson();
    }
    return data;
  }
}

class SoapEnvelope {
  SoapBody? soapBody;

  SoapEnvelope({this.soapBody});

  SoapEnvelope.fromJson(Map<String, dynamic> json) {
    soapBody = json['soap:Body'] != null
        ? new SoapBody.fromJson(json['soap:Body'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.soapBody != null) {
      data['soap:Body'] = this.soapBody!.toJson();
    }
    return data;
  }
}

class SoapBody {
  GetUtenteExtraResponse? getUtenteExtraResponse;

  SoapBody({this.getUtenteExtraResponse});

  SoapBody.fromJson(Map<String, dynamic> json) {
    getUtenteExtraResponse = json['GetUtenteExtraResponse'] != null
        ? new GetUtenteExtraResponse.fromJson(json['GetUtenteExtraResponse'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.getUtenteExtraResponse != null) {
      data['GetUtenteExtraResponse'] = this.getUtenteExtraResponse!.toJson();
    }
    return data;
  }
}

class GetUtenteExtraResponse {
  GetUtenteExtraResult? getUtenteExtraResult;

  GetUtenteExtraResponse({this.getUtenteExtraResult});

  GetUtenteExtraResponse.fromJson(Map<String, dynamic> json) {
    getUtenteExtraResult = json['GetUtenteExtraResult'] != null
        ? new GetUtenteExtraResult.fromJson(json['GetUtenteExtraResult'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.getUtenteExtraResult != null) {
      data['GetUtenteExtraResult'] = this.getUtenteExtraResult!.toJson();
    }
    return data;
  }
}

class GetUtenteExtraResult {
  ExpoisitorMapper? miatabella;

  GetUtenteExtraResult({this.miatabella});

  GetUtenteExtraResult.fromJson(Map<String, dynamic> json) {
    if (json['string'] != null) {
      miatabella = ExpoisitorMapper();
      try {
        miatabella!.ragionesociale =
            json['string'][0] != "NULL" ? json['string'][0] : null;
        miatabella!.nome = json['string'][1] != "NULL" ? json['string'][1] : null;
        miatabella!.cognome =
            json['string'][2] != "NULL" ? json['string'][2] : null;
        miatabella!.telefono =
            json['string'][3] != "NULL" ? json['string'][3] : null;
        miatabella!.cap = json['string'][4] != "NULL" ? json['string'][4] : null;
        miatabella!.email = json['string'][5] != "NULL" ? json['string'][5] : null;
        miatabella!.siglanazione =
            json['string'][6] != "NULL" ? json['string'][6] : null;
        miatabella!.siglaprovincia =
            json['string'][7] != "NULL" ? json['string'][7] : null;
        miatabella!.note = json['string'][8] != "NULL" ? json['string'][8] : null;
        miatabella!.foto1 = json['string'][9] != "NULL" ? json['string'][9] : null;
        miatabella!.foto2 =
            json['string'][10] != "NULL" ? json['string'][10] : null;
        miatabella!.foto3 =
            json['string'][11] != "NULL" ? json['string'][11] : null;
        miatabella!.valore =
            json['string'][12] != "NULL" ? json['string'][12] : null;
        miatabella!.idextra =
            json['string'][13] != "NULL" ? json['string'][13] : null;
      } catch (e) {
        miatabella = ExpoisitorMapper();
      }
    }
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.miatabella != null) {
      data['string'] = this.miatabella!.toJson();
    }
    return data;
  }
}
