import 'package:http/http.dart' as http;
import 'package:ticket_manager_flutter_app/model/course_model/course_object.dart';
import 'package:ticket_manager_flutter_app/model/expositor_code20_model/expositor_code20_model.dart';
import 'package:ticket_manager_flutter_app/model/expositor_mapper/expositor_mapper.dart';
import 'package:ticket_manager_flutter_app/model/expositor_model/expositor_model.dart';
import 'package:ticket_manager_flutter_app/network/vivaticket_api.dart';
import 'package:xml/xml.dart';
import 'package:xml2json/xml2json.dart';
import 'dart:convert';

import '../model/course_model/course.dart';
import '../utils/envirorment.dart';

class GetUserExtraByCode20Service {
  final myTransformer = Xml2Json();

  Future<ExpoisitorMapper> requestUserExtraBy20(int idUtilizzatore,
      int idManifestazione, String codice20, Envirorment envirorment) async {
    var envelope = '''
      <soap12:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap12="http://www.w3.org/2003/05/soap-envelope">
        <soap12:Body>
          <GetUtenteExtraByCode20 xmlns="http://tempuri.org/">            
            <codice20>$codice20</codice20>
            <idmanifestazione>$idManifestazione</idmanifestazione>
            <idutilizzatore>$idUtilizzatore</idutilizzatore>
          </GetUtenteExtraByCode20>
        </soap12:Body>
      </soap12:Envelope>
    ''';

    http.Response response = await http.post(
        Uri.parse(
            VivaticketApi.REQUEST_GET_UTENTE_EXTRA_BY_CODE_20(envirorment)),
        headers: {
          "Content-Type": "text/xml; charset=utf-8",
          //"SOAPAction": "http://tempuri.org/GetAllCity",
          //"Host": "www.i2isoftwares.com"
          "Accept": "text/xml"
        },
        body: envelope);

    var rawXmlResponse = response.body;

// Use the xml package's 'parse' method to parse the response.
    XmlDocument customParseXml = XmlDocument.parse(rawXmlResponse);
    myTransformer.parse(rawXmlResponse);
    var jsonResponse = myTransformer.toParker();
    Map<String, dynamic> responseJson = json.decode(jsonResponse);
    AutogeneratedExpositorCode20Response expositor =
        AutogeneratedExpositorCode20Response.fromJson(responseJson);

    //LoginResult result = LoginResult.fromJson(responseJsonjj["soap:Envelope"]["soap:Body"]["LoginUtenteResponse"]["LoginUtenteResult"]);
    print("DATAResult=" + response.body);

    return expositor.soapEnvelope!.soapBody!.getUtenteExtraByCode20Response!
        .getUtenteExtraByCode20Result!.miatabella!;
  }
}
