import 'package:http/http.dart' as http;
import 'package:ticket_manager_flutter_app/model/user_model/login_object.dart';
import 'package:ticket_manager_flutter_app/model/user_model/user.dart';
import 'package:ticket_manager_flutter_app/network/vivaticket_api.dart';
import 'package:ticket_manager_flutter_app/utils/envirorment.dart';
import 'package:xml/xml.dart';
import 'package:xml2json/xml2json.dart';
import 'dart:convert';

class LoginService {
  final myTransformer = Xml2Json();

  Future<User> requestLogin(
      String email, String password, Envirorment envirorment) async {
    var envelope = '''
      <soap12:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap12="http://www.w3.org/2003/05/soap-envelope">
        <soap12:Body>
          <LoginUtente xmlns="http://tempuri.org/">
            <email>$email</email>
            <pw>$password</pw>
          </LoginUtente>
        </soap12:Body>
      </soap12:Envelope>
    ''';

    http.Response response =
        await http.post(Uri.parse(VivaticketApi.REQUEST_LOGIN(envirorment)),
            headers: {
              "Content-Type": "text/xml; charset=utf-8",
              //"SOAPAction": "http://tempuri.org/GetAllCity",
              //"Host": "www.i2isoftwares.com"
              "Accept": "text/xml"
            },
            body: envelope);

    var rawXmlResponse = response.body;

// Use the xml package's 'parse' method to parse the response.
    XmlDocument customParseXml = XmlDocument.parse(rawXmlResponse);
    myTransformer.parse(rawXmlResponse);
    var jsonResponse = myTransformer.toParker();
    Map<String, dynamic> responseJson = json.decode(jsonResponse);
    AutogeneratedLogin loginResponse =
        AutogeneratedLogin.fromJson(responseJson);
    //LoginResult result = LoginResult.fromJson(responseJsonjj["soap:Envelope"]["soap:Body"]["LoginUtenteResponse"]["LoginUtenteResult"]);
    print("DATAResult=" + response.body);
    LoginUtenteResult loginUtenteResult = loginResponse
        .soapEnvelope!.soapBody!.loginUtenteResponse!.loginUtenteResult!;
    return User(
        id: int.parse(loginUtenteResult.valori![0].value!),
        email: email,
        password: password,
        userType: int.parse(loginUtenteResult.valori![3].value!),
        manifestationId: int.parse(loginUtenteResult.valori![1].value!),
        manifestationName: loginUtenteResult.valori![1].description!);
  }
}
