import 'package:ticket_manager_flutter_app/model/visitor_model/visitors_object.dart';
import 'package:ticket_manager_flutter_app/network/vivaticket_api.dart';
import 'package:ticket_manager_flutter_app/utils/envirorment.dart';
import 'package:xml2json/xml2json.dart';
import 'package:http/http.dart' as http;
import 'package:xml/xml.dart';
import 'dart:convert';

class VisitorsService {
  final myTransformer = Xml2Json();

  Future<int> requestVisitors(
      String idManifestazione, int idCorso, Envirorment envirorment) async {
    var envelope = '''
      <soap12:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap12="http://www.w3.org/2003/05/soap-envelope">
        <soap12:Body>
          <GetVisitatori xmlns="http://tempuri.org/">
            <idmanifestazione>$idManifestazione</idmanifestazione>
            <idcorso>$idCorso</idcorso>
          </GetVisitatori>
        </soap12:Body>
      </soap12:Envelope>
    ''';

    http.Response response =
        await http.post(Uri.parse(VivaticketApi.REQUEST_COURSES(envirorment)),
            headers: {
              "Content-Type": "text/xml; charset=utf-8",
              //"SOAPAction": "http://tempuri.org/GetAllCity",
              //"Host": "www.i2isoftwares.com"
              "Accept": "text/xml"
            },
            body: envelope);

    var rawXmlResponse = response.body;

// Use the xml package's 'parse' method to parse the response.
    XmlDocument customParseXml = XmlDocument.parse(rawXmlResponse);
    myTransformer.parse(rawXmlResponse);
    var jsonResponse = myTransformer.toParker();
    Map<String, dynamic> responseJson = json.decode(jsonResponse);

    AutogeneratedVisitors corseResponse =
        AutogeneratedVisitors.fromJson(responseJson);
    //LoginResult result = LoginResult.fromJson(responseJsonjj["soap:Envelope"]["soap:Body"]["LoginUtenteResponse"]["LoginUtenteResult"]);
    print("DATAResult=" + response.body);
    GetVisitatoriResponse getCorsiResult =
        corseResponse.soapEnvelope!.soapBody!.getVisitatoriResponse!;

    return int.parse(getCorsiResult.getVisitatoriResult!);
  }
}
