class AutogeneratedVisitors {
  SoapEnvelope? soapEnvelope;

  AutogeneratedVisitors({this.soapEnvelope});

  AutogeneratedVisitors.fromJson(Map<String, dynamic> json) {
    soapEnvelope = json['soap:Envelope'] != null
        ? new SoapEnvelope.fromJson(json['soap:Envelope'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.soapEnvelope != null) {
      data['soap:Envelope'] = this.soapEnvelope!.toJson();
    }
    return data;
  }
}

class SoapEnvelope {
  SoapBody? soapBody;

  SoapEnvelope({this.soapBody});

  SoapEnvelope.fromJson(Map<String, dynamic> json) {
    soapBody = json['soap:Body'] != null
        ? new SoapBody.fromJson(json['soap:Body'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.soapBody != null) {
      data['soap:Body'] = this.soapBody!.toJson();
    }
    return data;
  }
}

class SoapBody {
  GetVisitatoriResponse? getVisitatoriResponse;

  SoapBody({this.getVisitatoriResponse});

  SoapBody.fromJson(Map<String, dynamic> json) {
    getVisitatoriResponse = json['GetVisitatoriResponse'] != null
        ? new GetVisitatoriResponse.fromJson(json['GetVisitatoriResponse'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.getVisitatoriResponse != null) {
      data['GetVisitatoriResponse'] = this.getVisitatoriResponse!.toJson();
    }
    return data;
  }
}

class GetVisitatoriResponse {
  String? getVisitatoriResult;

  GetVisitatoriResponse({this.getVisitatoriResult});

  GetVisitatoriResponse.fromJson(Map<String, dynamic> json) {
    getVisitatoriResult = json['GetVisitatoriResult'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['GetVisitatoriResult'] = this.getVisitatoriResult;
    return data;
  }
}
