class AutogeneratedSetUtente {
  SoapEnvelope? soapEnvelope;

  AutogeneratedSetUtente({this.soapEnvelope});

  AutogeneratedSetUtente.fromJson(Map<String, dynamic> json) {
    soapEnvelope = json['soap:Envelope'] != null
        ? new SoapEnvelope.fromJson(json['soap:Envelope'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.soapEnvelope != null) {
      data['soap:Envelope'] = this.soapEnvelope!.toJson();
    }
    return data;
  }
}

class SoapEnvelope {
  SoapBody? soapBody;

  SoapEnvelope({this.soapBody});

  SoapEnvelope.fromJson(Map<String, dynamic> json) {
    soapBody = json['soap:Body'] != null
        ? new SoapBody.fromJson(json['soap:Body'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.soapBody != null) {
      data['soap:Body'] = this.soapBody!.toJson();
    }
    return data;
  }
}

class SoapBody {
  SetutenteappResponse? setutenteappResponse;

  SoapBody({this.setutenteappResponse});

  SoapBody.fromJson(Map<String, dynamic> json) {
    setutenteappResponse = json['SetutenteappResponse'] != null
        ? new SetutenteappResponse.fromJson(json['SetutenteappResponse'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.setutenteappResponse != null) {
      data['SetutenteappResponse'] = this.setutenteappResponse!.toJson();
    }
    return data;
  }
}

class SetutenteappResponse {
  String? setutenteappResult;

  SetutenteappResponse({this.setutenteappResult});

  SetutenteappResponse.fromJson(Map<String, dynamic> json) {
    setutenteappResult = json['SetutenteappResult'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['SetutenteappResult'] = this.setutenteappResult;
    return data;
  }
}
