class AutogeneratedCourse {
  SoapEnvelope? soapEnvelope;

  AutogeneratedCourse({this.soapEnvelope});

  AutogeneratedCourse.fromJson(Map<String, dynamic> json) {
    soapEnvelope = json['soap:Envelope'] != null
        ? new SoapEnvelope.fromJson(json['soap:Envelope'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.soapEnvelope != null) {
      data['soap:Envelope'] = this.soapEnvelope!.toJson();
    }
    return data;
  }
}

class SoapEnvelope {
  SoapBody? soapBody;

  SoapEnvelope({this.soapBody});

  SoapEnvelope.fromJson(Map<String, dynamic> json) {
    soapBody = json['soap:Body'] != null
        ? new SoapBody.fromJson(json['soap:Body'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.soapBody != null) {
      data['soap:Body'] = this.soapBody!.toJson();
    }
    return data;
  }
}

class SoapBody {
  GetCorsiResponse? getCorsiResponse;

  SoapBody({this.getCorsiResponse});

  SoapBody.fromJson(Map<String, dynamic> json) {
    getCorsiResponse = json['GetCorsiResponse'] != null
        ? new GetCorsiResponse.fromJson(json['GetCorsiResponse'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.getCorsiResponse != null) {
      data['GetCorsiResponse'] = this.getCorsiResponse!.toJson();
    }
    return data;
  }
}

class GetCorsiResponse {
  GetCorsiResult? getCorsiResult;

  GetCorsiResponse({this.getCorsiResult});

  GetCorsiResponse.fromJson(Map<String, dynamic> json) {
    getCorsiResult = json['GetCorsiResult'] != null
        ? new GetCorsiResult.fromJson(json['GetCorsiResult'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.getCorsiResult != null) {
      data['GetCorsiResult'] = this.getCorsiResult!.toJson();
    }
    return data;
  }
}

class GetCorsiResult {
  List<Valori>? valori;

  GetCorsiResult({this.valori});

  GetCorsiResult.fromJson(Map<String, dynamic> json) {
    if (json['Valori'] != null) {
      valori = <Valori>[];
      json['Valori'].forEach((v) {
        valori!.add(new Valori.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.valori != null) {
      data['Valori'] = this.valori!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Valori {
  String? value;
  String? description;
  String? count;

  Valori({this.value, this.description, this.count});

  Valori.fromJson(Map<String, dynamic> json) {
    value = json['Value'];
    description = json['Description'];
    count = json['Count'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['Value'] = this.value;
    data['Description'] = this.description;
    data['Count'] = this.count;
    return data;
  }
}
